import { PlaceRecords } from "../types/types";

export const mockTable: PlaceRecords = {
	meta: {
		limit: 100,
		page: 1,
		totalPages: 1,
		totalItems: 81,
	},
	data: [
		{
			id: "9",
			name: "Motley Crew: Woodstock",
			description: "A dynamic fitness studio in the creative Woodstock area.",
			category: "health",
			companyId: "1",
			address: "66 Albert Rd, Woodstock, Cape Town, 7915",
			coordinates: {
				lat: -33.930257,
				lon: 18.446058,
			},
		},
		{
			id: "80",
			name: "Hotel Montaigne",
			description: "Charming boutique hotel near the Eiffel Tower.",
			category: "guest_house",
			companyId: "51",
			address: "6 Avenue Montaigne, 75008 Paris, France",
			coordinates: {
				lat: 48.866711,
				lon: 2.30394,
			},
		},
		{
			id: "8",
			name: "DO Martial Arts: Green Point",
			description: "Martial arts studio offering a variety of classes in Green Point.",
			category: "health",
			companyId: "4",
			address: "25 Somerset Rd, Green Point, Cape Town, 8005",
			coordinates: {
				lat: -33.909544,
				lon: 18.410557,
			},
		},
		{
			id: "79",
			name: "Hotel Bayerischer Hof",
			description: "Historic luxury hotel in the heart of Munich.",
			category: "hotel",
			companyId: "50",
			address: "Promenadeplatz 2-6, 80333 Munich, Germany",
			coordinates: {
				lat: 48.141476,
				lon: 11.570049,
			},
		},
		{
			id: "78",
			name: "Le Pigalle Hotel",
			description: "Chic boutique hotel located in the vibrant Pigalle area.",
			category: "guest_house",
			companyId: "49",
			address: "9 Rue Frochot, 75009 Paris, France",
			coordinates: {
				lat: 48.88264,
				lon: 2.336533,
			},
		},
		{
			id: "77",
			name: "Steigenberger Hotel Hamburg",
			description: "Luxurious hotel located on the Alsterfleet canal.",
			category: "hotel",
			companyId: "48",
			address: "Heiligengeistbrücke 4, 20459 Hamburg, Germany",
			coordinates: {
				lat: 53.550444,
				lon: 9.988699,
			},
		},
		{
			id: "76",
			name: "Hotel Lutetia",
			description: "Historic luxury hotel on the Left Bank of Paris.",
			category: "hotel",
			companyId: "47",
			address: "45 Boulevard Raspail, 75006 Paris, France",
			coordinates: {
				lat: 48.851777,
				lon: 2.324144,
			},
		},
		{
			id: "75",
			name: "The Westin Paris - Vendôme",
			description: "Luxurious hotel with stunning views of the Eiffel Tower.",
			category: "hotel",
			companyId: "46",
			address: "3 Rue de Castiglione, 75001 Paris, France",
			coordinates: {
				lat: 48.86547,
				lon: 2.328017,
			},
		},
		{
			id: "74",
			name: "Le Bristol Paris",
			description: "Elegant luxury hotel in the heart of Paris.",
			category: "hotel",
			companyId: "45",
			address: "112 Rue du Faubourg Saint-Honoré, 75008 Paris, France",
			coordinates: {
				lat: 48.871667,
				lon: 2.316139,
			},
		},
		{
			id: "73",
			name: "Hotel de Crillon, A Rosewood Hotel",
			description: "Historic luxury hotel located on Place de la Concorde.",
			category: "hotel",
			companyId: "44",
			address: "10 Place de la Concorde, 75008 Paris, France",
			coordinates: {
				lat: 48.868595,
				lon: 2.321356,
			},
		},
		{
			id: "72",
			name: "Sofitel Munich Bayerpost",
			description: "Luxury hotel in a historic building in central Munich.",
			category: "hotel",
			companyId: "43",
			address: "Bayerstrasse 12, 80335 Munich, Germany",
			coordinates: {
				lat: 48.139126,
				lon: 11.558454,
			},
		},
		{
			id: "71",
			name: "Hotel Adlon Kempinski Berlin",
			description: "Iconic luxury hotel near the Brandenburg Gate.",
			category: "hotel",
			companyId: "42",
			address: "Unter den Linden 77, 10117 Berlin, Germany",
			coordinates: {
				lat: 52.516288,
				lon: 13.377687,
			},
		},
		{
			id: "70",
			name: "The Oyster Box",
			description: "Elegant hotel with stunning views of the Indian Ocean.",
			category: "hotel",
			companyId: "41",
			address: "2 Lighthouse Rd, Umhlanga Rocks, Durban, 4320",
			coordinates: {
				lat: -29.727352,
				lon: 31.085993,
			},
		},
		{
			id: "7",
			name: "Yoga Life: V&A Waterfront",
			description: "Peaceful yoga sessions in the iconic V&A Waterfront.",
			category: "health",
			companyId: "2",
			address: "19 Dock Rd, V&A Waterfront, Cape Town, 8001",
			coordinates: {
				lat: -33.90728,
				lon: 18.42098,
			},
		},
		{
			id: "69",
			name: "Beverly Hills Hotel",
			description: "Luxurious beachfront hotel in Umhlanga Rocks, Durban.",
			category: "hotel",
			companyId: "40",
			address: "54 Lighthouse Rd, Umhlanga Rocks, Durban, 4320",
			coordinates: {
				lat: -29.728735,
				lon: 31.085688,
			},
		},
	],
};
